// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.Models;

namespace TestTask.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestTask.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRemoved = false,
                            Name = "Конрад Керз",
                            Order = "Отдел Фронтэнда",
                            Position = "Разработчик",
                            TableNumber = 1000
                        },
                        new
                        {
                            Id = 2,
                            IsRemoved = false,
                            Name = "Марнеус Калгар",
                            Order = "Отдел Бэкэнда",
                            Position = "Разработчик",
                            TableNumber = 1001
                        },
                        new
                        {
                            Id = 3,
                            IsRemoved = false,
                            Name = "Робаут Жиллиман",
                            Order = "Отдел Фронтэнда",
                            Position = "Разработчик",
                            TableNumber = 1002
                        },
                        new
                        {
                            Id = 4,
                            IsRemoved = false,
                            Name = "Хорус Луперкаль",
                            Order = "IT-департамент",
                            Position = "Директор департамента",
                            TableNumber = 1003
                        },
                        new
                        {
                            Id = 5,
                            IsRemoved = false,
                            Name = "Леман Русс",
                            Order = "Отдел Фронтэнда",
                            Position = "ТимЛид",
                            TableNumber = 1004
                        },
                        new
                        {
                            Id = 6,
                            IsRemoved = false,
                            Name = "Лион Эль-Джонсон",
                            Order = "Отдел Бэкэнда",
                            Position = "Разработчик",
                            TableNumber = 1005
                        },
                        new
                        {
                            Id = 7,
                            IsRemoved = false,
                            Name = "Магнус Рыжый",
                            Order = "Отдел Бэкэнда",
                            Position = "ТимЛид",
                            TableNumber = 1006
                        });
                });

            modelBuilder.Entity("TestTask.Models.Person", b =>
                {
                    b.HasOne("TestTask.Models.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });
#pragma warning restore 612, 618
        }
    }
}
